// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQAhg8DPbGLREG1RKJO4tSnn1yPhTDikc',
    appId: '1:601001758505:web:7ed126b9cd7114cba9b138',
    messagingSenderId: '601001758505',
    projectId: 'movieom-25093',
    authDomain: 'movieom-25093.firebaseapp.com',
    storageBucket: 'movieom-25093.firebasestorage.app',
    measurementId: 'G-GME3JB7H80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-9Go6LGJ8To-Gtca0mIrsziUaEZH7iJQ',
    appId: '1:601001758505:android:3c172e9943379c87a9b138',
    messagingSenderId: '601001758505',
    projectId: 'movieom-25093',
    storageBucket: 'movieom-25093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWv4krtpPYvqe1yknvqJ-e8EsCIilsRw',
    appId: '1:601001758505:ios:85a285a019e74893a9b138',
    messagingSenderId: '601001758505',
    projectId: 'movieom-25093',
    storageBucket: 'movieom-25093.firebasestorage.app',
    iosBundleId: 'com.example.movieomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFWv4krtpPYvqe1yknvqJ-e8EsCIilsRw',
    appId: '1:601001758505:ios:85a285a019e74893a9b138',
    messagingSenderId: '601001758505',
    projectId: 'movieom-25093',
    storageBucket: 'movieom-25093.firebasestorage.app',
    iosBundleId: 'com.example.movieomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQAhg8DPbGLREG1RKJO4tSnn1yPhTDikc',
    appId: '1:601001758505:web:66e85a8987a9079ca9b138',
    messagingSenderId: '601001758505',
    projectId: 'movieom-25093',
    authDomain: 'movieom-25093.firebaseapp.com',
    storageBucket: 'movieom-25093.firebasestorage.app',
    measurementId: 'G-5N1NW1YEQ5',
  );
}
